# Generated by Django 2.2 on 2022-04-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB_N_01',
            fields=[
                ('modelID', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.FloatField()),
                ('actor', models.FloatField()),
                ('road', models.FloatField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Red_Line_Tracking',
            fields=[
                ('trackingID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('combinedModelList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinedModelList', to='vetoffice.FB_N_01')),
            ],
        ),
    ]
