# Generated by Django 2.2 on 2022-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0002_fb_n_01_red_line_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_n_01',
            name='actor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fb_n_01',
            name='host',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fb_n_01',
            name='road',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fb_n_01',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='red_line_tracking',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
